const translation = {
  pt_BR: {
    title: 'Seus dados',
    subtitle: 'Você pode mudar suas informações e clicar em salvar',
    button_save: 'Salvar',
    button_back: 'Voltar',
    label_name: 'NOME',
    label_email: 'E-MAIL',
    label_phone: 'TELEFONE',
    label_password: 'SENHA',
    label_password_confirm: 'CONFIRMAÇÃO DE SENHA',
    label_city: 'CIDADE',
    label_city_state: 'ESTADO',
    label_company: 'EMPRESA',
    label_country: 'PAÍS',
    error_notfound_name: 'Informe o nome',
    error_notfound_compay: 'Informe a empresa',
    error_notfound_telephone: 'Informe o telefone',
    error_notfound_city: 'Informe a cidade',
    error_notfound_city_state: 'Informe o estado da cidade',
    error_notfound_country: 'Informe o país',
    error_notfound_password: 'Informe a senha',
    error_notfound_password_confirm: 'Informe a confirmação de senha',
    error_min_password: 'A senha deve ter no mínimo 6 dígitos',
    error_password_not_match: 'A confirmação de senha não confere',
    message_updated: 'Seus dados foram atualizados',
    error_updated: 'Não foi possível atualizar os dados',
    password_info:
      'Para manter a sua segurança não mostramos a sua senha. Mas, você pode mudá-la qualquer momento.',
  },
  en_US: {
    title: 'Your Profile',
    subtitle: 'You can change your information and click save',
    button_save: 'Save',
    button_back: 'Back',
    label_name: 'NAME',
    label_email: 'E-MAIL',
    label_phone: 'TELEPHONE',
    label_password: 'PASSWORD',
    label_password_confirm: 'PASSWORD CONFIRM',
    label_city: 'CITY',
    label_city_state: 'STATE',
    label_company: 'COMPANY',
    label_country: 'COUNTRY',
    error_notfound_name: 'name is required',
    error_notfound_telephone: 'telephone is required',
    error_notfound_compay: 'company is required',
    error_notfound_city: 'city is required',
    error_notfound_city_state: 'state is required',
    error_notfound_country: 'country is required',
    error_notfound_password: 'password is required',
    error_notfound_password_confirm: 'password confirm is required',
    error_min_password: 'Password must be at least 6 digits',
    error_password_not_match: 'Password confirmation does not match',
    message_updated: 'Your data has been updated',
    error_updated: "Couldn't update data",
    password_info:
      'To maintain your security we do not show your password. But, you can change it anytime.',
  },
};

export default translation;
