const translation = {
  pt_BR: {
    'Plásticos Industriais': [
      {
        title: 'PPE – Éter de Polifenileno',
        items: [
          'Boas propriedades de isolamento elétrico',
          'Boa estabilidade dimensional',
          'Resistência a impacto superior',
          'Peso leve',
          'Capacidade de termoformagem',
        ],
      },
      {
        title: 'PP -Polipropileno',
        items: [
          'Excelente resistência química',
          'Baixa densidade e peso',
          'Alta pureza',
          'Baixíssima absorção de umidade',
          'Alta expansão térmica',
          'Alta flexibilidade',
          'Baixa tenacidade em temperatura negativa, sensível a impacto',
        ],
      },
      {
        title: 'PE – Polietileno',
        items: [
          'Baixa densidade em comparação a outros materiais',
          'Alta resistência a impacto, mesmo a baixas temperaturas',
          'Boa resistência ao desgaste',
          'Mínima absorção de umidade',
          'Resistência química excelente',
          'Alta resistência à corrosão',
          'Ausência de aderência',
          'Isolamento elétrico muito bom',
          'Alto amortecimento por vibração',
          'Tubulação para gás ou água potável',
        ],
      },
      {
        title: 'PMP – Polimetilpenteno',
        items: [
          'Baixa densidade',
          'Excelentes propriedades elétricas',
          'Baixa absorção de água',
          'Alta resistência à deformação',
          'Alta tenacidade',
          'Translucidez',
        ],
      },
      {
        title: 'ABS – Acrilonitrilo-butadieno-estireno',
        items: [
          'Eficiência de custos',
          'Disponibilidade em natural e preto',
          'Resistência a raios gama e raio-x',
          'Boa usinabilidade',
        ],
      },
    ],

    'Plásticos de Engenharia': [
      {
        title: 'POM – Polioximetileno Acetal',
        items: [
          'Alta resistência, rigidez e tenacidade',
          'Boa resistência ao impacto, mesmo a temperaturas baixas',
          'Baixa absorção de umidade (0,8% de absorção na saturação)',
          'Excelente resistência ao desgaste e propriedades deslizantes',
          'Excelente usinabilidade',
          'Boa resistência à deformação',
          'Alta estabilidade dimensional',
          'Boa resistência à hidrólise (até ~60°C)',
          'Excelente resiliência/ elasticidade',
        ],
      },
      {
        title: 'PA – Poliamida',
        items: [
          'Alta resistência ao desgaste',
          'Alta estabilidade térmica',
          'Excelente resistência e dureza',
          'Características significativas de amortecimento mecânico',
          'Boas propriedades de deslizamento',
          'Boa resistência química',
        ],
      },
      {
        title: 'PET – Polietileno Tereftalato',
        items: [
          'Alta resistência',
          'Alta rigidez e dureza',
          'Absorção de umidade muito baixa',
          'Boa resistência à deformação',
          'Baixo coeficiente de atrito e baixo desgaste a abrasão',
          'Resistência à hidrólise (até +70°C)',
          'Não adequado para contato com meio contendo >50% álcool',
          'Boa resistência química contra ácidos',
          'Boa adesão e habilidade de soldagem',
        ],
      },
      {
        title:
          'PCT-G – Poli-ciclohexilenodimetileno Tereftalato Glicol modificado',
        items: [
          'Excelente resistência ao impacto',
          'Boa resistência química',
          'Elevada resistência à radiação gama',
          'Alta transparência',
        ],
      },
      {
        title: 'PBT – Tereftalato de Polibutileno',
        items: [
          'Alta resistência e rigidez',
          'Estabilidade dimensional',
          'Baixa tendência à deformação',
          'Baixo atrito e boa resistência ao desgaste',
          'Boa resistência ao impacto',
          'Coeficiente de expansão térmica muito baixo',
          'Boa resistência química a ácidos',
          'Excelente resistência a soda cáustica e ao cloro',
          'Características elétricas muito boas',
          'Baixa absorção de umidade',
          'Boa habilidade de adesão e soldagem',
        ],
      },
      {
        title: 'PC - Policarbonato',
        items: [
          'Baixa densidade',
          'Translucidez (transparência para aplicações ópticas quando polidos)',
          'Resistência ao impacto',
          'Resistência química moderada (baixa resistência a solvente)',
          'Boa usinabilidade',
          'Excelente estabilidade dimensional',
          'Rigidez em uma ampla variedade de temperaturas',
        ],
      },
    ],

    'Plásticos Alta Performance': [
      {
        title: 'PEEK – Polieteretercetona',
        items: [
          'Alta resistência térmica e estabilidade ao calor',
          'Excelentes propriedades mecânicas e dureza',
          'Excelente resistência química',
          'Resistencia superior ao desgaste e propriedades de deslizamento',
        ],
      },
      {
        title: 'PAI – Poliamida – imida',
        items: [
          'Excelentes propriedades tribológicas e resistência ao desgaste Excelente resistência mecânica e rigidez a elevadas temperaturas Resistência a tração elevada',
          'Resistência a compressão elevada',
          'Alta temperatura de deflexão por calor Excelente coeficiente de expansão térmica Boa resistência ao impacto',
          'Excelente estabilidade térmica',
          'Boa usinabilidade',
          'Boa resistência química',
        ],
      },
      {
        title: 'PI – Poliimida',
        items: [
          'Polimiida de alta temperatura que não funde',
          'Estabilidade térmica a temperaturas constantes de 300°C (Picos de curta duração de até 400°C)',
          'Alta resistência de temperatura de até 470°C (HDT/A)',
          'Boas propriedades criogênicas abaixo de -270°C',
          'Alta resistência, módulo e rigidez também a altas temperaturas acima de 260°C',
          'Excelente isolamento térmico e elétrico',
          'Alta pureza, baixa desgaseificação em condições de vácuo',
          'Boa usinabilidade',
          'Inerentemente retardador de chama',
        ],
      },
      {
        title: 'PPS – Polisulfeto de fenileno',
        items: [
          'Alta característica de pureza',
          'Alta cristalinidade',
          'Bom isolamento elétrico',
          'Alta resistência mecânica',
          'Excelente resistência à alta temperatura',
          'Resistência química muito alta',
          'Resistência à deformação',
          'Estabilidade dimensional sobre diversas variações de  de temperatura e umidade',
        ],
      },
      {
        title: 'PPSU – Polifenilsulfona',
        items: [
          'Alta temperatura de operação (180°C)',
          'Boa compatibilidade química',
          'Excelente resistência à hidrólise (apropriada para esterilização à vapor repetitiva)',
          'Alta rigidez em um amplo intervalo de temperaturas',
          'Alta resistência ao impacto',
          'Alta estabilidade dimensional',
          'Excelente resistência contra radiação de energia (gama e raio-x)',
          'Boas propriedades de isolamento elétrico',
          'Características dielétricas favoráveis',
        ],
      },
      {
        title: 'PSU – Polissulfona',
        items: [
          'Alta temperatura de operação (160°C)',
          'Excelente resistência à hidrólise (adequada para esterilização a vapor repetitiva)',
          'Alta tenacidade, mesmo a baixas temperaturas',
          'Alta estabilidade dimensional',
          'Bom isolamento elétrico',
          'Alta resistência mecânica',
          'Alta rigidez',
          'Alta resistência à deformação em uma amplo intervalo de temperaturas',
          'Boa resistência à radiação',
        ],
      },
      {
        title: 'PES – Polietersulfona',
        items: [
          'Boas propriedades de isolamento elétrico',
          'Excelente resistência',
          'Translucidez',
          'Boa resistência à hidrólise',
        ],
      },
      {
        title: 'PEI – Polieterimida',
        items: [
          'Alta temperatura de operação permanente (170°C)',
          'Alta resistência mecânica',
          'Alta rigidez',
          'Alta resistência à deformação em um amplo intervalo de temperatura',
          'Alta estabilidade dimensional',
          'Excelente resistência à hidrólise (adequada para esterilização a vapor repetitiva)',
          'Bom isolamento elétrico',
          'Boa resistência à radiação',
          'Boa resistência química ao cloro e agentes de limpeza cáusticos/ácidos',
        ],
      },
      {
        title: 'PTFE – Politetrafluoroetileno',
        items: [
          'Resistência química extremamente alta',
          'Excelente resistência a temperatura alta e baixa (-200+260°C, curto prazo até 300°C)',
          'Baixo coeficiente de atrito',
          'Tensão de superfície extremamente baixa (praticamente nenhum material adere ao PTFE, difícil colagem ou soldagem)',
          'Alto coeficiente de expansão térmica',
          'Resistência/rigidez relativamente baixas',
          'Constante dielétrica baixa',
          'Resistência a chama',
        ],
      },
      {
        title: 'PVDF – Fluoreto de polivinilideno',
        items: [
          'Baixa densidade em comparação a outros fluoropolímeros',
          'Boa resistência mecânica em comparação a outros fluoropolímeros',
          'Alta temperatura de operação permanente (140°C)',
          'Praticamente sem absorção de umidade',
          'Boa estabilidade dimensional',
          'Alta resistência química',
          'Boa resistência à hidrólise',
          'Resistência UV',
          'Resistência à radiação',
          'Bom isolamento elétrico',
          'Alta resistência à abrasão',
        ],
      },
    ],
  },

  en_US: {
    'Industrial Plastics': [
      {
        title: 'PPE - Polyphenylene Ether',
        items: [
          'Good electrical insulation properties',
          'Good dimensional stability',
          'Superior impact resistance',
          'Lightweight',
          'Thermoforming capability',
        ],
      },
      {
        title: 'PP -Polypropylene',
        items: [
          'Excellent chemical resistance',
          'Low density and weight',
          'High purity',
          'Very low moisture absorption',
          'High thermal expansion',
          'High flexibility',
          'Low toughness at negative temperature, sensitive to impact',
        ],
      },
      {
        title: 'PE - Polyethylene',
        items: [
          'Low density compared to other materials',
          'High impact resistance, even at low temperatures',
          'Good wear resistance',
          'Minimum moisture absorption',
          'Excellent chemical resistance',
          'High corrosion resistance',
          'Absence of adherence',
          'Very good electrical insulation',
          'High vibration damping',
          'Piping for gas or drinking water',
        ],
      },
      {
        title: 'PMP - Polymethylpentene',
        items: [
          'Low density',
          'Excellent electrical properties',
          'Low water absorption',
          'High resistance to deformation',
          'High tenacity',
          'Translucency',
        ],
      },
      {
        title: 'ABS - Acrylonitrile-butadiene-styrene',
        items: [
          'Cost efficiency',
          'Availability in natural and black',
          'Resistance to gamma rays and x-rays',
          'Good machinability',
        ],
      },
    ],

    'Engineering Plastics': [
      {
        title: 'POM - Polyoxymethylene Acetal',
        items: [
          'High strength, rigidity and toughness',
          'Good impact resistance, even at low temperatures',
          'Low moisture absorption (0.8% absorption at saturation)',
          'Excellent wear resistance and sliding properties',
          'Excellent machinability',
          'Good resistance to deformation',
          'High dimensional stability',
          'Good resistance to hydrolysis (up to ~ 60 ° C)',
          'Excellent resilience / elasticity',
        ],
      },
      {
        title: 'PA - Polyamide',
        items: [
          'High wear resistance',
          'High thermal stability',
          'Excellent strength and toughness',
          'Significant mechanical damping characteristics',
          'Good sliding properties',
          'Good chemical resistance',
        ],
      },
      {
        title: 'PET - Polyethylene Terephthalate',
        items: [
          'High resistance',
          'High rigidity and hardness',
          'Very low moisture absorption',
          'Good resistance to deformation',
          'Low friction coefficient and low abrasion wear',
          'Resistance to hydrolysis (up to + 70 ° C)',
          'Not suitable for contact with medium containing> 50% alcohol',
          'Good chemical resistance against acids',
          'Good adhesion and welding ability',
        ],
      },
      {
        title:
          'PCT-G - Modified Poly-cyclohexylenedimethylene Terephthalate Glycol',
        items: [
          'Excellent impact resistance',
          'Good chemical resistance',
          'High resistance to gamma radiation',
          'High transparency',
        ],
      },
      {
        title: 'PBT - Polybutylene Terephthalate',
        items: [
          'High strength and stiffness',
          'Dimensional stability',
          'Low tendency to deformation',
          'Low friction and good wear resistance',
          'Good impact resistance',
          'Very low thermal expansion coefficient',
          'Good chemical resistance to acids',
          'Excellent resistance to caustic soda and chlorine',
          'Very good electrical characteristics',
          'Low moisture absorption',
          'Good adhesion and welding skills',
        ],
      },
      {
        title: 'PC - Polycarbonate',
        items: [
          'Low density',
          'Translucency (transparency for optical applications when polished)',
          'Impact resistance',
          'Moderate chemical resistance (low solvent resistance)',
          'Good machinability',
          'Excellent dimensional stability',
          'Stiffness over a wide range of temperatures',
        ],
      },
    ],

    'High Performance Plastics': [
      {
        title: 'PEEK - Polyetheretherketone',
        items: [
          'High thermal resistance and heat stability',
          'Excellent mechanical properties and hardness',
          'Excellent chemical resistance',
          'Superior wear resistance and sliding properties',
        ],
      },
      {
        title: 'PAI  - Polyamide - imide',
        items: [
          'Excellent tribological properties and wear resistance Excellent mechanical resistance and stiffness at high temperatures High tensile strength',
          'High compressive strength',
          'High heat deflection temperature Excellent thermal expansion coefficient Good impact resistance',
          'Excellent thermal stability',
          'Good machinability',
          'Good chemical resistance',
        ],
      },
      {
        title: 'PI - Polyimide',
        items: [
          'High temperature polyimide that does not melt',
          'Thermal stability at constant temperatures of 300 ° C (Short-term peaks up to 400 ° C)',
          'High temperature resistance up to 470 ° C (HDT / A)',
          'Good cryogenic properties below -270 ° C',
          'High strength, modulus and stiffness also at high temperatures above 260 ° C',
          'Excellent thermal and electrical insulation',
          'High purity, low degassing under vacuum conditions',
          'Good machinability',
          'Inherently flame retardant',
        ],
      },
      {
        title: 'PPS - Phenylene polysulfide',
        items: [
          'High purity characteristic',
          'High crystallinity',
          'Good electrical insulation',
          'High mechanical strength',
          'Excellent resistance to high temperature',
          'Very high chemical resistance',
          'Resistance to deformation',
          'Dimensional stability over different temperature and humidity variations',
        ],
      },
      {
        title: 'PPSU - Polyphenylsulfone',
        items: [
          'High operating temperature (180 ° C)',
          'Good chemical compatibility',
          'Excellent resistance to hydrolysis (suitable for repetitive steam sterilization)',
          'High rigidity over a wide temperature range',
          'High impact resistance',
          'High dimensional stability',
          'Excellent resistance against energy radiation (gamma and x-ray)',
          'Good electrical insulation properties',
          'Favorable dielectric characteristics',
        ],
      },
      {
        title: 'PSU - Polysulfone',
        items: [
          'High operating temperature (160 ° C)',
          'Excellent resistance to hydrolysis (suitable for repetitive steam sterilization)',
          'High toughness, even at low temperatures',
          'High dimensional stability',
          'Good electrical insulation',
          'High mechanical strength',
          'High rigidity',
          'High resistance to deformation over a wide temperature range',
          'Good radiation resistance',
        ],
      },
      {
        title: 'PES - Polyethersulfone',
        items: [
          'Good electrical insulation properties',
          'Excellent resistance',
          'Translucency',
          'Good resistance to hydrolysis',
        ],
      },
      {
        title: 'PEI - Polyetherimide',
        items: [
          'High permanent operating temperature (170 ° C)',
          'High mechanical strength',
          'High rigidity',
          'High resistance to deformation over a wide temperature range',
          'High dimensional stability',
          'Excellent resistance to hydrolysis (suitable for repetitive steam sterilization)',
          'Good electrical insulation',
          'Good radiation resistance',
          'Good chemical resistance to chlorine and caustic / acid cleaning agents',
        ],
      },
      {
        title: 'PTFE - Polytetrafluoroethylene',
        items: [
          'Extremely high chemical resistance',
          'Excellent resistance to high and low temperature (-200 + 260 ° C, short term up to 300 ° C)',
          'Low friction coefficient',
          'Extremely low surface tension (virtually no material adheres to PTFE, difficult to glue or weld)',
          'High coefficient of thermal expansion',
          'Relatively low strength / stiffness',
          'Low dielectric constant',
          'Flame resistance',
        ],
      },
      {
        title: 'PVDF - Polyvinylidene fluoride',
        items: [
          'Low density compared to other fluoropolymers',
          'Good mechanical strength compared to other fluoropolymers',
          'High permanent operating temperature (140 ° C)',
          'Virtually no moisture absorption',
          'Good dimensional stability',
          'High chemical resistance',
          'Good resistance to hydrolysis',
          'UV resistance',
          'Radiation resistance',
          'Good electrical insulation',
          'High abrasion resistance',
        ],
      },
    ],
  },
};

export default translation;
