export default [
  { value: 'AFG', label: 'Afeganistão' },
  { value: 'ZAF', label: 'África do Sul' },
  { value: 'ALB', label: 'Albânia' },
  { value: 'DEU', label: 'Alemanha' },
  { value: 'AND', label: 'Andorra' },
  { value: 'AGO', label: 'Angola' },
  { value: 'AIA', label: 'Anguilla' },
  { value: 'ATA', label: 'Antártida' },
  { value: 'ATG', label: 'Antígua e Barbuda' },
  { value: 'ANT', label: 'Antilhas Holandesas' },
  { value: 'SAU', label: 'Arábia Saudita' },
  { value: 'DZA', label: 'Argélia' },
  { value: 'ARG', label: 'Argentina' },
  { value: 'ARM', label: 'Armênia' },
  { value: 'ABW', label: 'Aruba' },
  { value: 'AUS', label: 'Austrália' },
  { value: 'AUT', label: 'Áustria' },
  { value: 'AZE', label: 'Azerbaijão' },
  { value: 'BHS', label: 'Bahamas' },
  { value: 'BHR', label: 'Bahrein' },
  { value: 'BGD', label: 'Bangladesh' },
  { value: 'BRB', label: 'Barbados' },
  { value: 'BLR', label: 'Belarus' },
  { value: 'BEL', label: 'Bélgica' },
  { value: 'BLZ', label: 'Belize' },
  { value: 'BEN', label: 'Benin' },
  { value: 'BMU', label: 'Bermudas' },
  { value: 'BOL', label: 'Bolívia' },
  { value: 'BIH', label: 'Bósnia-Herzegóvina' },
  { value: 'BWA', label: 'Botsuana' },
  { value: 'BRA', label: 'Brasil' },
  { value: 'BRN', label: 'Brunei' },
  { value: 'BGR', label: 'Bulgária' },
  { value: 'BFA', label: 'Burkina Fasso' },
  { value: 'BDI', label: 'Burundi' },
  { value: 'BTN', label: 'Butão' },
  { value: 'CPV', label: 'Cabo Verde' },
  { value: 'CMR', label: 'Camarões' },
  { value: 'KHM', label: 'Camboja' },
  { value: 'CAN', label: 'Canadá' },
  { value: 'KAZ', label: 'Cazaquistão' },
  { value: 'TCD', label: 'Chade' },
  { value: 'CHL', label: 'Chile' },
  { value: 'CHN', label: 'China' },
  { value: 'CYP', label: 'Chipre' },
  { value: 'SGP', label: 'Cingapura' },
  { value: 'COL', label: 'Colômbia' },
  { value: 'COG', label: 'Congo' },
  { value: 'PRK', label: 'Coréia do Norte' },
  { value: 'KOR', label: 'Coréia do Sul' },
  { value: 'CIV', label: 'Costa do Marfim' },
  { value: 'CRI', label: 'Costa Rica' },
  { value: 'HRV', label: 'Croácia (Hrvatska)' },
  { value: 'CUB', label: 'Cuba' },
  { value: 'DNK', label: 'Dinamarca' },
  { value: 'DJI', label: 'Djibuti' },
  { value: 'DMA', label: 'Dominica' },
  { value: 'EGY', label: 'Egito' },
  { value: 'SLV', label: 'El Salvador' },
  { value: 'ARE', label: 'Emirados Árabes Unidos' },
  { value: 'ECU', label: 'Equador' },
  { value: 'ERI', label: 'Eritréia' },
  { value: 'SVK', label: 'Eslováquia' },
  { value: 'SVN', label: 'Eslovênia' },
  { value: 'ESP', label: 'Espanha' },
  { value: 'USA', label: 'Estados Unidos' },
  { value: 'EST', label: 'Estônia' },
  { value: 'ETH', label: 'Etiópia' },
  { value: 'FJI', label: 'Fiji' },
  { value: 'PHL', label: 'Filipinas' },
  { value: 'FIN', label: 'Finlândia' },
  { value: 'FRA', label: 'França' },
  { value: 'GAB', label: 'Gabão' },
  { value: 'GMB', label: 'Gâmbia' },
  { value: 'GHA', label: 'Gana' },
  { value: 'GEO', label: 'Geórgia' },
  { value: 'GIB', label: 'Gibraltar' },
  { value: 'GBR', label: 'Grã-Bretanha (Reino Unido, UK)' },
  { value: 'GRD', label: 'Granada' },
  { value: 'GRC', label: 'Grécia' },
  { value: 'GRL', label: 'Groelândia' },
  { value: 'GLP', label: 'Guadalupe' },
  { value: 'GUM', label: 'Guam (Território dos Estados Unidos)' },
  { value: 'GTM', label: 'Guatemala' },
  { value: 'GGY', label: 'Guernsey' },
  { value: 'GUY', label: 'Guiana' },
  { value: 'GUF', label: 'Guiana Francesa' },
  { value: 'GIN', label: 'Guiné' },
  { value: 'GNQ', label: 'Guiné Equatorial' },
  { value: 'GNB', label: 'Guiné-Bissau' },
  { value: 'HTI', label: 'Haiti' },
  { value: 'NLD', label: 'Holanda' },
  { value: 'HND', label: 'Honduras' },
  { value: 'HKG', label: 'Hong Kong' },
  { value: 'HUN', label: 'Hungria' },
  { value: 'YEM', label: 'Iêmen' },
  { value: 'BVT', label: 'Ilha Bouvet (Território da Noruega)' },
  { value: 'IMN', label: 'Ilha do Homem' },
  { value: 'CXR', label: 'Ilha Natal' },
  { value: 'PCN', label: 'Ilha Pitcairn' },
  { value: 'REU', label: 'Ilha Reunião' },
  { value: 'ALA', label: 'Ilhas Aland' },
  { value: 'CYM', label: 'Ilhas Cayman' },
  { value: 'CCK', label: 'Ilhas Cocos' },
  { value: 'COM', label: 'Ilhas Comores' },
  { value: 'COK', label: 'Ilhas Cook' },
  { value: 'FRO', label: 'Ilhas Faroes' },
  { value: 'FLK', label: 'Ilhas Falkland (Malvinas)' },
  { value: 'SGS', label: 'Ilhas Geórgia do Sul e Sandwich do Sul' },
  {
    value: 'HMD',
    label: 'Ilhas Heard e McDonald (Território da Austrália)',
  },
  { value: 'MNP', label: 'Ilhas Marianas do Norte' },
  { value: 'MHL', label: 'Ilhas Marshall' },
  { value: 'UMI', label: 'Ilhas Menores dos Estados Unidos' },
  { value: 'NFK', label: 'Ilhas Norfolk' },
  { value: 'SYC', label: 'Ilhas Seychelles' },
  { value: 'SLB', label: 'Ilhas Solomão' },
  { value: 'SJM', label: 'Ilhas Svalbard e Jan Mayen' },
  { value: 'TKL', label: 'Ilhas Tokelau' },
  { value: 'TCA', label: 'Ilhas Turks e Caicos' },
  { value: 'VIR', label: 'Ilhas Virgens (Estados Unidos)' },
  { value: 'VGB', label: 'Ilhas Virgens (Inglaterra)' },
  { value: 'WLF', label: 'Ilhas Wallis e Futuna' },
  { value: 'IND', label: 'índia' },
  { value: 'IDN', label: 'Indonésia' },
  { value: 'IRN', label: 'Irã' },
  { value: 'IRQ', label: 'Iraque' },
  { value: 'IRL', label: 'Irlanda' },
  { value: 'ISL', label: 'Islândia' },
  { value: 'ISR', label: 'Israel' },
  { value: 'ITA', label: 'Itália' },
  { value: 'JAM', label: 'Jamaica' },
  { value: 'JPN', label: 'Japão' },
  { value: 'JEY', label: 'Jersey' },
  { value: 'JOR', label: 'Jordânia' },
  { value: 'KEN', label: 'Kênia' },
  { value: 'KIR', label: 'Kiribati' },
  { value: 'KWT', label: 'Kuait' },
  { value: 'LAO', label: 'Laos' },
  { value: 'LVA', label: 'Látvia' },
  { value: 'LSO', label: 'Lesoto' },
  { value: 'LBN', label: 'Líbano' },
  { value: 'LBR', label: 'Libéria' },
  { value: 'LBY', label: 'Líbia' },
  { value: 'LIE', label: 'Liechtenstein' },
  { value: 'LTU', label: 'Lituânia' },
  { value: 'LUX', label: 'Luxemburgo' },
  { value: 'MAC', label: 'Macau' },
  { value: 'MKD', label: 'Macedônia (República Yugoslava)' },
  { value: 'MDG', label: 'Madagascar' },
  { value: 'MYS', label: 'Malásia' },
  { value: 'MWI', label: 'Malaui' },
  { value: 'MDV', label: 'Maldivas' },
  { value: 'MLI', label: 'Mali' },
  { value: 'MLT', label: 'Malta' },
  { value: 'MAR', label: 'Marrocos' },
  { value: 'MTQ', label: 'Martinica' },
  { value: 'MUS', label: 'Maurício' },
  { value: 'MRT', label: 'Mauritânia' },
  { value: 'MYT', label: 'Mayotte' },
  { value: 'MEX', label: 'México' },
  { value: 'FSM', label: 'Micronésia' },
  { value: 'MOZ', label: 'Moçambique' },
  { value: 'MDA', label: 'Moldova' },
  { value: 'MCO', label: 'Mônaco' },
  { value: 'MNG', label: 'Mongólia' },
  { value: 'MNE', label: 'Montenegro' },
  { value: 'MSR', label: 'Montserrat' },
  { value: 'MMR', label: 'Myanma' },
  { value: 'NAM', label: 'Namíbia' },
  { value: 'NRU', label: 'Nauru' },
  { value: 'NPL', label: 'Nepal' },
  { value: 'NIC', label: 'Nicarágua' },
  { value: 'NER', label: 'Níger' },
  { value: 'NGA', label: 'Nigéria' },
  { value: 'NIU', label: 'Niue' },
  { value: 'NOR', label: 'Noruega' },
  { value: 'NCL', label: 'Nova Caledônia' },
  { value: 'NZL', label: 'Nova Zelândia' },
  { value: 'OMN', label: 'Omã' },
  { value: 'PLW', label: 'Palau' },
  { value: 'PAN', label: 'Panamá' },
  { value: 'PNG', label: 'Papua-Nova Guiné' },
  { value: 'PAK', label: 'Paquistão' },
  { value: 'PRY', label: 'Paraguai' },
  { value: 'PER', label: 'Peru' },
  { value: 'PYF', label: 'Polinésia Francesa' },
  { value: 'POL', label: 'Polônia' },
  { value: 'PRI', label: 'Porto Rico' },
  { value: 'PRT', label: 'Portugal' },
  { value: 'QAT', label: 'Qatar' },
  { value: 'KGZ', label: 'Quirguistão' },
  { value: 'CAF', label: 'República Centro-Africana' },
  { value: 'COD', label: 'República Democrática do Congo' },
  { value: 'DOM', label: 'República Dominicana' },
  { value: 'CZE', label: 'República Tcheca' },
  { value: 'ROM', label: 'Romênia' },
  { value: 'RWA', label: 'Ruanda' },
  { value: 'RUS', label: 'Rússia (antiga URSS) - Federação Russa' },
  { value: 'ESH', label: 'Saara Ocidental' },
  { value: 'VCT', label: 'Saint Vincente e Granadinas' },
  { value: 'ASM', label: 'Samoa Americana' },
  { value: 'WSM', label: 'Samoa Ocidental' },
  { value: 'SMR', label: 'San Marino' },
  { value: 'SHN', label: 'Santa Helena' },
  { value: 'LCA', label: 'Santa Lúcia' },
  { value: 'BLM', label: 'São Bartolomeu' },
  { value: 'KNA', label: 'São Cristóvão e Névis' },
  { value: 'MAF', label: 'São Martim' },
  { value: 'STP', label: 'São Tomé e Príncipe' },
  { value: 'SEN', label: 'Senegal' },
  { value: 'SLE', label: 'Serra Leoa' },
  { value: 'SRB', label: 'Sérvia' },
  { value: 'SYR', label: 'Síria' },
  { value: 'SOM', label: 'Somália' },
  { value: 'LKA', label: 'Sri Lanka' },
  { value: 'SPM', label: 'St. Pierre and Miquelon' },
  { value: 'SWZ', label: 'Suazilândia' },
  { value: 'SDN', label: 'Sudão' },
  { value: 'SWE', label: 'Suécia' },
  { value: 'CHE', label: 'Suíça' },
  { value: 'SUR', label: 'Surilabel' },
  { value: 'TJK', label: 'Tadjiquistão' },
  { value: 'THA', label: 'Tailândia' },
  { value: 'TWN', label: 'Taiwan' },
  { value: 'TZA', label: 'Tanzânia' },
  { value: 'IOT', label: 'Território Britânico do Oceano índico' },
  { value: 'ATF', label: 'Territórios do Sul da França' },
  { value: 'PSE', label: 'Territórios Palestinos Ocupados' },
  { value: 'TMP', label: 'Timor Leste' },
  { value: 'TGO', label: 'Togo' },
  { value: 'TON', label: 'Tonga' },
  { value: 'TTO', label: 'Trinidad and Tobago' },
  { value: 'TUN', label: 'Tunísia' },
  { value: 'TKM', label: 'Turcomenistão' },
  { value: 'TUR', label: 'Turquia' },
  { value: 'TUV', label: 'Tuvalu' },
  { value: 'UKR', label: 'Ucrânia' },
  { value: 'UGA', label: 'Uganda' },
  { value: 'URY', label: 'Uruguai' },
  { value: 'UZB', label: 'Uzbequistão' },
  { value: 'VUT', label: 'Vanuatu' },
  { value: 'VAT', label: 'Vaticano' },
  { value: 'VEN', label: 'Venezuela' },
  { value: 'VNM', label: 'Vietnã' },
  { value: 'ZMB', label: 'Zâmbia' },
  { value: 'ZWE', label: 'Zimbábue' },
];
